apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hour.fullname" . }}
  labels:
    {{- include "hour.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "hour.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "hour.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
        - name: APP_VERSION
          value: {{ .Values.image.tag | quote }}
        ports:
          - name: http
            containerPort: {{ .Values.port }}
            protocol: TCP
