apiVersion: v1
kind: Service
metadata:
  name: {{ include "hour.fullname" . }}
  labels:
    {{- include "hour.labels" . | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.port }}
  selector:
    {{- include "hour.selectorLabels" . | nindent 4 }}
